### ISSUE TITLE
todo for Xiaoai

### ISSUE THREAD

**Issue by hugoledoux** [cityjson/ninja#15]
- [x] add support for GeometryTemplates
- [ ] add streaming from a WFS3 server, see [this](https://github.com/hugoledoux/cityjson_ogcapi/blob/master/best-practice.md#streaming)
- [x] There should be a radio-button for textures on/off
- [x] Integrate your work into the vuejs components
- [ ] Make the visualisation *fast*
- [ ] Backend in flask: https://palletsprojects.com/p/flask/
  - My example for CityJSON and OGC-API: https://github.com/hugoledoux/cityjson_ogcapi
- [ ] Upload of textures (which are stored on the flask-server)
- [ ] If still time, we find extra tasks later

**Comment by Alena0915** [comment]
- [ ] fix another geometry type "GeometryInstance"

**Comment by Alena0915** [comment]
> * [ ]  add support for GeometryTemplates
> * [ ]  add streaming from a WFS3 server, see [this](https://github.com/hugoledoux/cityjson_ogcapi/blob/master/best-practice.md#streaming)
> * [ ]  There should be a radio-button for textures on/off
> * [x ]  Integrate your work into the vuejs components
> * [x ]  Make the visualisation _fast_
> * [ ]  Backend in flask: https://palletsprojects.com/p/flask/
>   
>   * My example for CityJSON and OGC-API: https://github.com/hugoledoux/cityjson_ogcapi
> * [ ]  Upload of textures (which are stored on the flask-server)
> * [ ]  If still time, we find extra tasks later

**Comment by liberostelios** [comment]
That's for @xiaoai-li

**Comment by liberostelios** [comment]
This is outdated now. Will try to incorporate @xiaoai-li contributions in future versions of [cityjson-threejs-loader](https://github.com/cityjson/cityjson-threejs-loader).

@xiaoai-li Thanks so much for your time!
